version: '3.8'

services:
  server:
    # Tell Docker Compose to use the .dev Dockerfile
    build:
      context: ./Server
      dockerfile: Dockerfile.dev
    volumes:
      # Mount your local source code into the container
      - ./Server/src:/usr/src/app/src
    ports:
      - "3001:3001"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      # Mount your local source code for live-reloading
      - ./client:/app
      - /app/node_modules # Do not map the host node_modules
    ports:
      # The Vue dev server runs on 8080
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - server

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
    