version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile.prod
    # In production, we don't mount volumes for code
    volumes: []
    # No need to expose port to host if it's behind a reverse proxy like Nginx
    # But we expose it here for direct access if needed
    #W Will be added later
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - server